export const questionnaire = [
  {
    question_number: 1,
    question: "How many days a week do spend working?",
    choices: [
      "A.	Less than two days - I've perfected the game",
      "B.	2-4 days - Enjoying some freedom",
      "C.	4-5 days - Spend most of my week in or thinking about the business",
      "D.	5-6 days - I'm consumed by the business, I struggle for freedom",
      "E.	7 days, I'm out of control!",
    ],
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 5,
    use_percentage: false,
  },
  {
    question_number: 2,
    question:
      "How much holiday time have you booked in this year (not including weekends)",
    choices: [
      "A.	The business doesn't depend on me I travel 3-6 months of the year",
      "B.	I take 4 weeks off every year, I love to recharge",
      "C.	I take off a week here and there, its unpredictable",
      "D.	I try to take off public holidays, but end up working anyway",
      "E.	I haven't had a break in 2 years…",
    ],
    answer: 0,
    scoring: "subract 10 points for each 1 eg 1=10 - 2=20",
    max_score: 5,
    use_percentage: false,
  },
  {
    question_number: 3,
    question: "How much do you get to take out of the business to live on?",
    choices: [
      "A.	Over $250,00 p/a",
      "B.	$150,00-$249,999 p/a",
      "C.	$80,000-$149,999 p/a ",
      "D.	$30,00-$79,999 p/a",
      "E.	Less than $30,000 p/a",
    ],
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 5,
    use_percentage: false,
  },
  {
    question_number: 4,
    question: "Does the business help you live your best life?",
    choices: [
      "A.	Yes, absolutely. I am fit, happy and healthy",
      "B.	Feeling pretty good about life but could tweak a few things",
      "C.	It's ok…",
      "D.	Stressed and not eating so well, sleep's impacted but it'll get better ",
      "E.	I just don't have time to think about that and I don't know where to start",
    ],
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 5,
    use_percentage: false,
  },
  {
    question_number: 5,
    question: "What kind of business are you building?",
    choices: [
      "A.	An empire that works well without me",
      "B.	I'm building the business to sell as my retirement plan",
      "C.	I've got a decent team, great systems and marketing works like a dream",
      "D.	I'll work with a small team",
      "E.	I just want to work on my own",
    ],
    answer: 0,
    scoring: "add 10 points for each 1 eg 1=10 - 2=20",
    max_score: 5,
    use_percentage: false,
  },
  { choices: [] },
];
